apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: arduinni.azurecr.io/catalogo-pedelogo:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongodb-secret
